[package]
name = "egg-herbie"
version = "0.2.0"
authors = [ "Oliver Flatt <oflatt@gmail.com>", "Max Willsey <me@mwillsey.com>" ]
edition = "2018"


[dependencies]
egg = { git = "https://github.com/oflatt/egg", rev = "5639c971c0f5eff43fd072e3245946e9c38303a7" }

log = "0.4"
indexmap = "1"
libc = "0.2.71"
smallvec = "1.4.0"

num-rational = "0.3.0"
num-bigint = "0.3.0"
num-traits = "0.2.12"
env_logger = { version = "0.7", default-features = false }

[lib]
name = "egg_math"
crate-type = ["rlib", "cdylib"]

[profile.test]
debug = true
opt-level = 1

[profile.release]
debug = true
lto = "fat"
codegen-units = 1
