name: Plugin tests

on: [push]

env:
  RUST_BACKTRACE: full

jobs:
  distribute:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    name: "Standalone Executable Tests"
    steps:
      - uses: actions/checkout@master
      - name: "Install Racket"
        uses: Bogdanp/setup-racket@v1.3.1
        with:
            version: stable
      - name: Install Rust compiler
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            default: true
            override: true
            components: rustfmt, clippy
      - uses: actions/checkout@master
      - name: "Install dependencies"
        run: make install
      - name: "Build standalone executable"
        run: make distribute-minimal
      - name: "Uninstall local Herbie instance"
        run: raco pkg remove herbie egg-herbie
      - name: "Test executable (report tool)"
        run: herbie-compiled/bin/herbie report --threads yes bench/hamming graphs
