name: Build and test egglog on all three OSes

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Install Racket"
        uses: Bogdanp/setup-racket@v1.9
        with:
            version: 8.7
      - name: Install Rust compiler
        uses: actions-rs/toolchain@v1.0.6
        with:
            toolchain: stable
            default: true
            override: true
            components: rustfmt, clippy
      - run: cd src/egglog/egg-smol && cargo clippy --tests
      - run: cd src/egglog/egg-smol && cargo test
      - run: cd src/egglog/egg-smol && cargo fmt -- --check
      - run: cd src/egglog/egg-smol && cargo build --release
