name: Unit, Integration, and Plugin tests

on: [push]

env:
  RUST_BACKTRACE: full

jobs:
  unit-tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Install Packages"
        run: sudo apt-get install -y libmpfr6 libmpfr-dev
      - name: "Install Racket"
        uses: Bogdanp/setup-racket@v0.5
      - uses: actions/checkout@master
      - name: "Install dependencies"
        run: raco pkg install --name herbie --no-cache --auto src/
      - run: raco test src/ infra/

  hamming:
    name: "Integration tests (Hamming)"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: [ '7.5', '7.9', '8.0' ]
        precision: [ 'binary32', 'binary64' ]
    steps:
      - name: "Install Packages"
        run: sudo apt-get install -y libmpfr6 libmpfr-dev
      - name: "Install Racket"
        uses: Bogdanp/setup-racket@v0.5
        with:
          version: ${{ matrix.racket-version }}
      - uses: actions/checkout@master
      - name: "Install dependencies"
        run: raco pkg install --name herbie --no-cache --auto src/
      - run: racket infra/travis.rkt --precision ${{ matrix.precision }} --seed 0 bench/hamming/

  softposit:
    name: "Plugin tests (Posits)"
    runs-on: ubuntu-latest
    needs: [ 'hamming' ]
    steps:
      - name: "Install Packages"
        run: sudo apt-get install -y libmpfr6 libmpfr-dev
      - name: "Install Racket"
        uses: Bogdanp/setup-racket@v0.5
      - uses: actions/checkout@master
      - name: "Install dependencies"
        run: raco pkg install --name herbie --no-cache --auto src/
      - name: "Check out softposit-herbie master"
        uses: actions/checkout@master
        with:
          repository: herbie-fp/softposit-herbie
          path: plugin
      - name: "Install SoftPosit support"
        run: raco pkg install --no-cache --auto --name softposit-herbie plugin/
      - run: racket infra/travis.rkt --precision posit16 --seed 0 plugin/bench/posits.fpcore

  complex:
    name: "Plugin tests (Complex)"
    runs-on: ubuntu-latest
    needs: [ 'hamming' ]
    steps:
      - name: "Install Packages"
        run: sudo apt-get install -y libmpfr6 libmpfr-dev
      - name: "Install Racket"
        uses: Bogdanp/setup-racket@v0.5
      - uses: actions/checkout@master
      - name: "Install dependencies"
        run: raco pkg install --name herbie --no-cache --auto src/
      - name: "Check out complex-herbie master"
        uses: actions/checkout@master
        with:
          repository: herbie-fp/complex-herbie
          path: plugin
      - name: "Install Complex support"
        run: raco pkg install --no-cache --auto --name complex-herbie plugin/
      - run: racket infra/travis.rkt --seed 0 plugin/test.fpcore
