name: Unit tests

on: [push]

env:
  RUST_BACKTRACE: full

jobs:
  unit-tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Install Packages"
        run: sudo apt-get install -y libmpfr6 libmpfr-dev
      - name: "Install Racket"
        uses: Bogdanp/setup-racket@v1.9
        with:
          version: 8.7
      - name: Install Rust compiler
        uses: actions-rs/toolchain@v1.0.6
        with:
            toolchain: stable
            default: true
            override: true
            components: rustfmt, clippy
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Install dependencies"
        run: make install
      - run: raco test src/ infra/
